### ISSUE TITLE
whitespace stripping

### ISSUE THREAD

**Issue by ryleyb** [oalders/html-restrict#36]
In version v2.2.2, this happens:

```
ryleyb$ perl -MHTML::Restrict -e "print '\''.HTML::Restrict->new()->process('B ').\"'\n\""
'B'
```

Before I dig further, is that expected?  I would have expected my whitespace to come through unmolested.

**Comment by oalders** [comment]
It is expected, but you can turn it off via `trim => 0`.

```sh
perl -MHTML::Restrict -e "print '\''.HTML::Restrict->new(trim => 0)->process('B ').\"'\n\""
'B '
```

**Comment by ryleyb** [comment]
Thank you, I had the feeling it was a "Friday afternoon" type issue!

**Comment by oalders** [comment]
I appreciate you getting in touch about it.  Feel free to reach out if you run into any other issues.  :)
